//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateServiceClient.SimpleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleService.ISimpleService")]
    public interface ISimpleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/get_Id", ReplyAction="http://tempuri.org/ISimpleService/get_IdResponse")]
        System.Guid get_Id();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/get_Id", ReplyAction="http://tempuri.org/ISimpleService/get_IdResponse")]
        System.Threading.Tasks.Task<System.Guid> get_IdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/ProcessMessage", ReplyAction="http://tempuri.org/ISimpleService/ProcessMessageResponse")]
        string ProcessMessage(string message, System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/ProcessMessage", ReplyAction="http://tempuri.org/ISimpleService/ProcessMessageResponse")]
        System.Threading.Tasks.Task<string> ProcessMessageAsync(string message, System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/IsAllowed", ReplyAction="http://tempuri.org/ISimpleService/IsAllowedResponse")]
        bool IsAllowed(string[] message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/IsAllowed", ReplyAction="http://tempuri.org/ISimpleService/IsAllowedResponse")]
        System.Threading.Tasks.Task<bool> IsAllowedAsync(string[] message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceChannel : PrivateServiceClient.SimpleService.ISimpleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleServiceClient : System.ServiceModel.ClientBase<PrivateServiceClient.SimpleService.ISimpleService>, PrivateServiceClient.SimpleService.ISimpleService {
        
        public SimpleServiceClient() {
        }
        
        public SimpleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid get_Id() {
            return base.Channel.get_Id();
        }
        
        public System.Threading.Tasks.Task<System.Guid> get_IdAsync() {
            return base.Channel.get_IdAsync();
        }
        
        public string ProcessMessage(string message, System.Guid clientId) {
            return base.Channel.ProcessMessage(message, clientId);
        }
        
        public System.Threading.Tasks.Task<string> ProcessMessageAsync(string message, System.Guid clientId) {
            return base.Channel.ProcessMessageAsync(message, clientId);
        }
        
        public bool IsAllowed(string[] message) {
            return base.Channel.IsAllowed(message);
        }
        
        public System.Threading.Tasks.Task<bool> IsAllowedAsync(string[] message) {
            return base.Channel.IsAllowedAsync(message);
        }
    }
}
