//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P12Proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Name = new Name();
            this.Address = new Address();
        }
    
        public int Id { get; set; }
    
        public Name Name { get; set; }
        public Address Address { get; set; }
    }
}
